name = "rusticket-telegram-admin"
main = "src/index.ts"
compatibility_date = "2026-09-01"

[vars]
TELEGRAM_ADMIN_ID = "5723340037"

[[d1_databases]]
binding = "ADMIN_DB"
database_name = "rusticket-telegram-admin-state"
database_id = "080f82b2-ed11-43e4-8333-2968d30bee5b"

